### ISSUE TITLE
When will you be able to expose code and data sets？

### ISSUE THREAD

**Issue by MLsmaller** [geliuhao/3DHandShapePosefromRGB#3]
Hello, I am very interested in your project. May I ask when this project will be open source? Thank you

**Comment by josecyc** [comment]
Same here! we are building a neural interface to get signals from the forearm and predict a mesh from those signals. This is great to build our dataset.

**Comment by MLsmaller** [comment]
> Same here! we are building a neural interface to get signals from the forearm and predict a mesh from those signals. This is great to build our dataset.

Have you seen any other open source projects on the web that can predict a mesh, preferably by hand.Thank you very much

**Comment by josecyc** [comment]
Hi @MLsmaller, no I haven't seen any other that predicts a mesh. I am also interested in it though.

**Comment by 3d-hand-shape** [comment]
We have released the code and datasets in this repo: https://github.com/3d-hand-shape/hand-graph-cnn/
