### ISSUE TITLE
Root Positions?

### ISSUE THREAD

**Issue by namheegordonkim** [geliuhao/3DHandShapePosefromRGB#6]
Hi,

According to your paper, the model should be capable of producing pose estimates for single RGB image inputs. However, there is this "pose_root" variable required to feedforward the model, and seems like your paper states that we need the xyz-coordinate of the wrist. Doesn't this require depth information at test time? If not, how do we impute this value in the wild? Thanks.

**Comment by www516717402** [comment]
@namheegordonkim I also meet this issue.Need feed some prior information in net forward.

**Comment by 3d-hand-shape** [comment]
In this paper, to get the absolute 3D hand pose and mesh, we need to know the 3D coordinate of the root joint, which can be predicted by the 3D hand detection from the entire image at test time.
